description: >
  Generates the workflow based on dynamic config.
parameters:
  branch:
    type: string
    default: << pipeline.git.branch >>
    description: >
      Branch where the config files are stored
  config-output:
    type: string
    default: "workflows.yml"
    description: >
      The name of the generated config file.
  config-source:
    type: string
    default: ".circleci/src"
    description: >
      The location of the config files to pack.
steps:
  - run:
      name: Pack CircleCI config files
      environment:
        BRANCH: << parameters.branch >>
        CONFIG_OUTPUT: << parameters.config-output >>
        CONFIG_SOURCE: << parameters.config-source >>
      command: <<include(scripts/pack-config.sh)>>
